name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Most used languages (detailed)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics.plugin.languages.details.svg
          base: ""
          plugin_languages: true
          plugin_languages_indepth: true
          repositories_affiliations: owner
          repositories: 200
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          # Temporarily comment this out while debugging:
          # plugin_languages_ignored: >-
          #   html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot

